version: '2'
services:
  ngapp-app:
    image: ngapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://ngapp-mssql:1433;database=ngapp
      - JHIPSTER_CACHE_REDIS_SERVER=redis://ngapp-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://ngapp-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://ngapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://ngapp-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8690:8690
  ngapp-mssql:
    extends:
      file: mssql.yml
      service: ngapp-mssql
  ngapp-redis:
    extends:
      file: redis.yml
      service: ngapp-redis
  ngapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: ngapp-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
